### ISSUE TITLE
[Feature] 반려견 기능 구현

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#10]
## 🔥 Issue
반려견 기능 구현
## ✅ TODO
- [x]  반려견 추가
- [x] 정보 수정
- [x] 질병 / 알러지 조회
- [x] #11
- [ ] 섭취 영양소 조회
- [x] 반려견 조회
- [ ] 영양제 추천
- [ ] 부족 / 과잉 영양소 알림
