### ISSUE TITLE
[Infra] cicd 작업 및 Redis 의존성 및 환경 추가 

### ISSUE THREAD

**Issue by dionisos198** [CEOS-PAT-PLATE/BackEnd#13]
## 🔥 Issue
CICD 작업을 위한 yml 파일을 작성하고 
미리 redis 컨테이너를 올려 둘 것이기 떄문에 redis 환경 및 의존성을 세팅한다. 

## ✅ TODO
- [x]  cicd yml 파일 작성
- [x] redis 라이브러리 추가
- [x] redis 환경 설정
