### ISSUE TITLE
[Refactor] 질병에 좋은 약 명시 및 추천 로직 수정 

### ISSUE THREAD

**Issue by dionisos198** [CEOS-PAT-PLATE/BackEnd#146]
## 🔥 Issue
이슈 관련 내용을 입력하세요.

질병에 좋은 약을 명시한다.

영양성분에 따른 추천 영양제 로직을 일부 수정한다. 

## ✅ TODO
- [ ]  해야 할 작업을 추가하세요.
- [ ] 질병에 좋은 약 명시
- [ ] 영양성분에 따른 추천 영양제 로직 일부 수정
- [ ] 테스트 코드 작성
