### ISSUE TITLE
[Feature] 과잉 / 부족 영양소 조회

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#24]
## 🔥 Issue
반려견이 오늘 한 식사에서 부족한 영양소와 과잉 섭취한 영양소를 조회함
## ✅ TODO
- [x]  부족 영양소 조회
- [x] 과잉 영양소 조회
- [x] 허용 범위 결정 및 적용 (최적의 영양소에서 어느 정도까지는 적절 영양소로 인정할 것인지? %를 정해야함)
