### ISSUE TITLE
[Feature] 섭취 칼로리 조회

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#25]
## 🔥 Issue
반려견이 섭취한 칼로리를 조회합니다

## ✅ TODO
- [x]  활동량에 따른 적정 칼로리 계산
- [x] 오늘 섭취한 칼로리 반환
- [x] 적정 칼로리 대비 오늘 섭취한 칼로리의 비율 반환
