### ISSUE TITLE
[Feature] 기존 작성한 기능의 테스트 진행

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#29]
## 🔥 Issue
추가한 기능에 대한 테스트를 진행하지 않았어서, 서비스의 테스트를 진행합니다.

## ✅ TODO
- [x] 반려견 추가
- [x] 유저의 모든 펫 조회
- [x] 유저의 특정 펫 조회
- [x] 반려견 정보 수정
- [x] 프로필 이미지 수정
- [x] 알러지 조회
- [x] 질병 조회
- [x] 섭취 영양분 조회
- [x] 섭취 영양분의 적정 섭취량 대비 비율 조회
- [x] 과잉 섭취 영양분 조회
- [x] 부족 섭취 영양분 조회
- [x] 섭취 칼로리 조회
- [x] 적정 칼로리 조회
- [x] 적정 섭취 칼로리 대비 실 섭취 칼로리 비율 조회
