### ISSUE TITLE
[Refactoring] 부족 영양분 별 추천 영양제 리팩토링 , Swagger 세팅 , 테스트 코드 

### ISSUE THREAD

**Issue by dionisos198** [CEOS-PAT-PLATE/BackEnd#41]
## 🔥 Issue
그 동안 하지 못한 짬처리 용도 이슈입니다

## ✅ TODO
- [ ]  부족 영양분 별 추천 영양제 리팩토링 (확정 아님) 
- [ ]  swagger 세팅 
- [ ] 영양제 컨트롤러 swagger 적용 
- [ ] 영양제 repository, service , controller 테스트 코드
