### ISSUE TITLE
[Feature] 하루 식사 기능 구현

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#46]
## 🔥 Issue
- 자연식, 사료, 포장 간식 추가, 조회, 삭제 기능을 구현합니다.

## ✅ TODO
- [x] 자연식
- [x] 하루섭취 자연식
- [x] 하루섭취 사료
- [x] 하루섭취 포장간식
- [x] 즐겨찾기 자연식
- [x] 하루섭취 즐겨찾기 자연식
- [x] 즐겨찾기 사료
- [x] 하루섭취 즐겨찾기 사료
- [x] 즐겨찾기 포장 간식
- [x] 하루섭취 즐겨찾기 포장 간식
- [x] 섭취 음식 추가 시 하루 식사에 영양소 추가되도록 구현
