### ISSUE TITLE
[Feature] 영양제 리스트 조회 , 삭제 기능 

### ISSUE THREAD

**Issue by dionisos198** [CEOS-PAT-PLATE/BackEnd#47]
## 🔥 Issue
현재 DB에 저장되어 있는 영양제 리스트를 전부 가져온다.
또한 ID 기반으로 영양제를 삭제하는 기능을 구현한다. 
또한 Url 이 기존 크기(255) 보다 큰 경우가 있어서 칼럼의 length 를 수정한다. 

## ✅ TODO
- [x]  Url 칼럼 수정(255->500)
- [x]  영양제 리스트 조회
- [x] 영양제 리스트 조회 테스트 코드 
- [x] 영양제 ID 기반 삭제 
- [x] 영양제 ID 기반 삭제 테스트 코드
