### ISSUE TITLE
[Feature] 부족, 과잉, 적정 영양소 저장

### ISSUE THREAD

**Issue by riceCakeSsamanKo** [CEOS-PAT-PLATE/BackEnd#66]
## 🔥 Issue
섭취한 하루식사의 부족, 과잉, 적정 저장소를 저장하기 위한 테이블을 생성하고 이를 위한 로직을 구현합니다.

## ✅ TODO
- [ ] 부족, 과잉, 적정 영양소 엔티티 생성
- [ ] DailyMeal과 연관관계 연결
- [ ] crd 기능을 위한 리포지터리, 서비스 구현
- [ ] 서비스 테스트
- [ ] 컨트롤러 구현
